name: Deploy Task Manager Bot

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd task_manager_bot
            git pull origin main
            
            # Remove old .env file
            rm .env
    
            # Write secrets into .env file on the remote machine
            echo "BOT_API_TOKEN=${{ secrets.BOT_API_TOKEN }}" >> .env
    
            docker-compose down --volumes=false
            docker-compose up --build -d